/
INSERT INTO  adm.tipo_documento VALUES (78,'CERTIFICADO DE INCAPACIDAD',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (79,'RESUMEN DE LA ATENCIÓN O EPICRISIS',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (80,'FORMATO DE INVESTIGACIÓN',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (81,'FURIPS',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (82,'SOAT O CARTA DEL VEHÍCULO INVOLUCRADO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (83,'CERTIFICADO DE LICENCIA DE MATERNIDAD',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (84,'CERTIFICADO DE LICENCIA PREPARTO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (85,'REGISTRO CIVIL DE NACIMIENTO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (86,'CERTIFICADO DE LICENCIA DE MATERNIDAD (COMPARTIDA). ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (87,'SOLICITUD FORMAL DE LICENCIA PARENTAL ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (88,'CERTIFICADO DE LICENCIA DE MATERNIDAD  A FAVOR DE QUIEN CORRESPONDA',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (89,'REGISTRO CIVIL DE NACIMIENTO ENTREGADO EN ADOPCIÓN',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (90,'ACTA DE ENTREGA DEL MENOR DE EDAD POR PARTE DEL ICBF O INSTITUCIÓN AUTORIZADA ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (91,'CALIFICACIÓN DEL ORIGEN Y PORCENTAJE DE PÉRDIDA DE CAPACIDAD LABORAL PCL VIGENTE',null,SYSDATE,user,'INCAPACIDADES',NULL);
/
--*************************************************************************
--** OBJETIVO             : OBTENER LOS DOCUMENTOS POR SUBTIPO DE INCAPACIDAD
--** ESQUEMA              : RHU
--** TABLA                : SUBTIPO_DOCUMENTOS
--** AUTOR                : DESIERRA
--** FECHA CREACION       : 2023-04-03
--*************************************************************************


--*************************************************************************
--** FORMATO TABLA
--*************************************************************************
CREATE TABLE RHU.SUBTIPO_DOCUMENTOS (
    SUDO_CODIGO              NUMBER PRIMARY KEY,
    TPD_CODIGO               NUMBER,
    SUBTIPOINC_CODIGO        NUMBER,
    SUDO_REQUERIDO           VARCHAR2(15) NOT NULL,
    SUDO_ESTADO              VARCHAR2(15) NOT NULL,
    AUD_USUARIO              VARCHAR2(15) NOT NULL,
    AUD_FECHA                DATE NOT NULL
)

ALTER TABLE RHU.SUBTIPO_DOCUMENTOS ADD CONSTRAINT  SUDO_ESTADO CHECK (SUDO_ESTADO IN ('ACTIVO' , 'DESACTIVADO'));
ALTER TABLE RHU.SUBTIPO_DOCUMENTOS ADD  CONSTRAINT FK_SUBTPDOCUMENTO FOREIGN KEY (TPD_CODIGO) REFERENCES ADM.TIPO_DOCUMENTO(TPD_CODIGO);
ALTER TABLE RHU.SUBTIPO_DOCUMENTOS ADD  CONSTRAINT FK_SUBTPSUBTP FOREIGN KEY (SUBTIPOINC_CODIGO) REFERENCES RHU.SUBTIPO_INCAPACIDAD(SUBTIPOINC_CODIGO);
/
--*************************************************************************
--** COMENTARIOS DE LAS COLUMNAS DE LA TABLA, NO EXCEDER LOS 30 CARACTERES.
--*************************************************************************
COMMENT ON TABLE RHU.TIPO_INCAPACIDAD IS
'Tabla para administrar los resgitros de tipo de incapacidades.';

COMMENT ON COLUMN RHU.TIPO_INCAPACIDAD.TIPOINC_CODIGO   IS
'ID del registro de tipo de incapacidad.';

COMMENT ON COLUMN RHU.TIPO_INCAPACIDAD.TIPOINC_NOMBRE   IS
'Nombre del registro de tipo de incapacidad.';

COMMENT ON COLUMN RHU.TIPO_INCAPACIDAD.TIPOINC_ESTADO   IS
'Estado del registro de tipo de incapacidad.';

COMMENT ON COLUMN RHU.TIPO_INCAPACIDAD.AUD_USUARIO   IS
'Nombre de usuario que realiza la accion.';

COMMENT ON COLUMN RHU.TIPO_INCAPACIDAD.AUD_FECHA   IS
'Fecha de usuario que realiza la accion.';

/
--*************************************************************************
--** SE CREA EL SINONIMO DE LA TABLA.
--*************************************************************************
GRANT SELECT ON RHU.SUBTIPO_DOCUMENTOS TO PUBLIC;
CREATE PUBLIC SYNONYM SUBTIPO_DOCUMENTOS FOR RHU.SUBTIPO_DOCUMENTOS;
GRANT ALL ON RHU.SUBTIPO_DOCUMENTOS TO PUBLIC;

--*************************************************************************
--** CREACION DE SECUENCIA.
--*************************************************************************
CREATE SEQUENCE RHU.SEQ_SUBTIPO_DOCUMENTOS INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
GRANT ALL ON RHU.SEQ_SUBTIPO_DOCUMENTOS TO PUBLIC;
/
INSERT INTO  adm.tipo_documento VALUES (78,'CERTIFICADO DE INCAPACIDAD',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (79,'RESUMEN DE LA ATENCIÓN O EPICRISIS',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (80,'FORMATO DE INVESTIGACIÓN',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (81,'FURIPS',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (82,'SOAT O CARTA DEL VEHÍCULO INVOLUCRADO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (83,'CERTIFICADO DE LICENCIA DE MATERNIDAD',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (84,'CERTIFICADO DE LICENCIA PREPARTO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (85,'REGISTRO CIVIL DE NACIMIENTO ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (86,'CERTIFICADO DE LICENCIA DE MATERNIDAD (COMPARTIDA). ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (87,'SOLICITUD FORMAL DE LICENCIA PARENTAL ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (88,'CERTIFICADO DE LICENCIA DE MATERNIDAD  A FAVOR DE QUIEN CORRESPONDA',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (89,'REGISTRO CIVIL DE NACIMIENTO ENTREGADO EN ADOPCIÓN',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (90,'ACTA DE ENTREGA DEL MENOR DE EDAD POR PARTE DEL ICBF O INSTITUCIÓN AUTORIZADA ',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (91,'CALIFICACIÓN DEL ORIGEN Y PORCENTAJE DE PÉRDIDA DE CAPACIDAD LABORAL PCL VIGENTE',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (92,'CERTIFICADO DE PAGO DE INCAPACIDADES EMITIDO POR EL FONDO DE PENSIONES',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (93,'CARTA DEL FONDO DE PENSIONES DONDE REMITE EL CASO DEL USUARIO A LA EPS',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (94,'CALIFICACIÓN DE PÉRDIDA DE CAPACIDAD LABORAL VIGENTE',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (95,'COPIA DE LA HISTORIA CLÍNICA DE LOS ESPECIALISTAS DE LOS ÚLTIMOS SEIS MESES',null,SYSDATE,user,'INCAPACIDADES',NULL);
INSERT INTO  adm.tipo_documento VALUES (96,'FURAT',null,SYSDATE,user,'INCAPACIDADES',NULL);
/
describe RHU.SUBTIPO_DOCUMENTOS
/
---INCAPACIDAD INICIAL (NO PRÓRROGA DE 1 Y 2 DÍAS) 1
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('1', '78', '1', 'S', 'ACTIVO', USER, SYSDATE);

---Incapacidad Prórroga o Mayor a 2 días cobrable al SGSSS 2
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('2', '78', '2', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('3', '79', '2', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('4', '80', '2', 'S', 'ACTIVO', USER, SYSDATE);

--Si es Incapacidad por SOAT (No Laboral) 3
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('5', '78', '3', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('6', '79', '3', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('7', '80', '3', 'S', 'ACTIVO', USER, SYSDATE);

--INCAPACIDADES SUPERIORES A 540 DÍAS 4
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('8', '78', '4', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('9', '92', '4', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('10', '93', '4', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('11', '94', '4', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('12', '95', '4', 'S', 'ACTIVO', USER, SYSDATE);
/

--INCAPACIDAD LICENCIA MATERNIDAD Y/O ABORTO 8
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('13', '83',  '8', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('14', '84',  '8', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('15', '79', '8', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('16', '85', '8', 'N', 'ACTIVO', USER, SYSDATE);

--LICENCIA DE PATERNIDAD 9
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('17', '85',  '9', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('18', '79',  '9', 'N', 'ACTIVO', USER, SYSDATE);

--LICENCIA DE MATERNIDAD O PATERNIDAD COMPARTIDA / FLEXIBLE 10
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('19', '88',  '10', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('20', '85',  '10', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('21', '86',  '10', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('22', '87',  '10', 'N', 'ACTIVO', USER, SYSDATE);

-- LICENCIA DE MATERNIDAD POR EXTENSIÓN 11
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('23', '88',  '11', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('24', '89',  '11', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('25', '90',  '11', 'N', 'ACTIVO', USER, SYSDATE);


-- LINCAPACIDAD ACCIDENTE DE TRABAJO 6
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('26', '78',  '6', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('27', '89',  '6', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('28', '96',  '6', 'N', 'ACTIVO', USER, SYSDATE);

-- LINCAPACIDAD ACCIDENTE DE TRABAJO 7
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('29', '78',  '7', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('30', '79',  '7', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('31', '96',  '7', 'N', 'ACTIVO', USER, SYSDATE);


-- INCAPACIDAD ENFERMEDAD LABORAL 5
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('32', '78',  '5', 'S', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('33', '79',  '5', 'N', 'ACTIVO', USER, SYSDATE);
INSERT INTO "RHU"."SUBTIPO_DOCUMENTOS" VALUES ('34', '91',  '5', 'N', 'ACTIVO', USER, SYSDATE);


COMMIT;
/


select * from adm.PROPIEDADES_DOCUMENTO;
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('96','96','O','M','V',SYSDATE,USER);

INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('78','78','O','M','V',SYSDATE,USER);
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('79','79','O','M','V',SYSDATE,USER);
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('80','80','O','M','V',SYSDATE,USER);
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('81','81','O','M','V',SYSDATE,USER);
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO) VALUES ('82','82','O','M','V',SYSDATE,USER);
INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('83','83','O','M','V',SYSDATE,USER);     
 INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('84','84','O','M','V',SYSDATE,USER);  
 INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('85','85','O','M','V',SYSDATE,USER);                                                                                                                                                                                                 
 INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('86','86','O','M','V',SYSDATE,USER);   
  INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO) VALUES ('87','87','O','M','V',SYSDATE,USER);  
 INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('88','88','O','M','V',SYSDATE,USER);  
  INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO) VALUES ('89','89','O','M','V',SYSDATE,USER);      
  INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('90','90','O','M','V',SYSDATE,USER);   
  INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO) VALUES ('91','91','O','M','V',SYSDATE,USER);   
  INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO) VALUES ('92','92','O','M','V',SYSDATE,USER);     
   INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('93','93','O','M','V',SYSDATE,USER);   
   INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('94','94','O','M','V',SYSDATE,USER);   
   INSERT INTO ADM.PROPIEDADES_DOCUMENTO (PRD_CODIGO, TPD_CODIGO,TDT_ORIGEN,TDT_OBLIGATORIO,TDT_VERSION,AUD_FECHA,AUD_USUARIO)VALUES ('95','95','O','M','V',SYSDATE,USER);                                                                                                                                                                                                                                                                                                                                                                                                      
/
ALTER TABLE RHU.incapacidad  DROP CONSTRAINT C_INC_ESTADO;
ALTER TABLE RHU.incapacidad ADD  
CONSTRAINT "C_INC_ESTADO" CHECK (INC_ESTADO
IN ('CAP', 'PEN', 'APR', 'REH', 'ANU', 'DEV', 'RAT', 'RNN', 'INR', 'INP', 'RIN','RRI','CPT')) ENABLE;

CREATE SEQUENCE RHU.SEQ_INC_NUMERO INCREMENT BY 101002 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
GRANT ALL ON RHU.SEQ_INC_NUMERO TO PUBLIC;

CREATE OR REPLACE TRIGGER "RHU"."DB_INC_NUMERO" 
Before
  INSERT ON  RHU.INCAPACIDAD REFERENCING NEW AS NEW
  FOR EACH ROW

  Begin
	Select SEQ_INC_NUMERO.Nextval
      INTO :NEW.INC_NUMERO
      FROM dual;	
  --
EXCEPTION
  WHEN OTHERS THEN
    raise_application_error(-20001, 'Error secuencia DB_INC_NUMERO'||sqlerrm);
End;