/
--*************************************************************************
--** OBJETIVO             : SUBTIPOS DE INCAPACIDAD
--** ESQUEMA              : RHU
--** TABLA                : SUBTIPO_INCAPACIDAD
--** AUTOR                : JARGUMEDO
--** FECHA CREACION       : 2023-03-06
--*************************************************************************


--*************************************************************************
--** FORMATO TABLA
--*************************************************************************
CREATE TABLE RHU.SBT_INCAPACIDAD (
    SBT_CODIGO               NUMBER PRIMARY KEY,
    TIP_CODIGO               NUMBER NOT NULL,
    SBT_NOMBRE               VARCHAR2(100) NOT NULL,
    SBT_ESTADO               VARCHAR2(15) NOT NULL,
    AUD_USUARIO              VARCHAR2(15) NOT NULL,
    AUD_FECHA                DATE NOT NULL
);


--*************************************************************************
--** RELACION DE LLAVES FORANEAS
--*************************************************************************
ALTER TABLE RHU.SBT_INCAPACIDAD ADD CONSTRAINT SUBTIPOINC_ESTADO_C CHECK (SBT_ESTADO IN ('ACTIVO' , 'DESACTIVADO'));
ALTER TABLE RHU.SBT_INCAPACIDAD ADD CONSTRAINT TIP_CODIGO_FK FOREIGN KEY (TIP_CODIGO) REFERENCES RHU.TIP_INCAPACIDAD (TIP_CODIGO);

/
--*************************************************************************
--** COMENTARIOS DE LAS COLUMNAS DE LA TABLA, NO EXCEDER LOS 30 CARACTERES.
--*************************************************************************
COMMENT ON TABLE RHU.SUBTIPO_INCAPACIDAD IS
'Tabla para administrar los registros de subtipo de incapacidades.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.SUBTIPOINC_CODIGO   IS
'ID del registro de subtipo de incapacidad.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.TIPOINC_CODIGO   IS
'Llave foranea para la relacion entre tipo de incapacidad.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.SUBTIPOINC_NOMBRE   IS
'Nombre del subtipo de incapacidad.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.SUBTIPOINC_ESTADO   IS
'Estado del subtipo de incapacidad.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.AUD_USUARIO   IS
'Nombre de usuario que realiza la accion.';

COMMENT ON COLUMN RHU.SUBTIPO_INCAPACIDAD.AUD_FECHA   IS
'Fecha de usuario que realiza la accion.';

/
--*************************************************************************
--** SE CREA EL SINONIMO DE LA TABLA.
--*************************************************************************
GRANT SELECT ON RHU.SBT_INCAPACIDAD TO PUBLIC;
CREATE PUBLIC SYNONYM SBT_INCAPACIDAD FOR RHU.SBT_INCAPACIDAD;
GRANT ALL ON RHU.SBT_INCAPACIDAD TO PUBLIC;

--*************************************************************************
--** CREACION DE SECUENCIA.
--*************************************************************************
CREATE SEQUENCE RHU.SBT_INCAPACIDAD INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE;
GRANT ALL ON RHU.SBT_INCAPACIDAD TO PUBLIC;
/
--- ENFERMEDAD GENERAL------
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (1,1,'INCAPACIDAD INICIAL (NO PRÓRROGA DE 1 Y 2 DÍAS)','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (2,1,'INCAPACIDAD PRÓRROGA O MAYOR A 2 DÍAS COBRABLE AL SGSSS','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (3,1,'SI ES INCAPACIDAD POR SOAT (NO LABORAL)','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (4,1,'INCAPACIDADES SUPERIORES A 540 DÍAS','ACTIVO',USER,SYSDATE);

--- ENFERMEDAD LABORAL------
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (5,3,'INCAPACIDAD ENFERMEDAD LABORAL','ACTIVO',USER,SYSDATE);


--- ACCIDENTE LABORAL------
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (6,2,'INCAPACIDAD ACCIDENTE DE TRABAJO','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (7,2,'INCAPACIDAD ACCIDENTE DE TRABAJO ORIGINADAS POR ACCIDENTE DE TRÁNSITO','ACTIVO',USER,SYSDATE);

-- LICENCIA MATERNIDAD, ABORTO Y PATERNIDAD ---
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (8,4,'INCAPACIDAD LICENCIA MATERNIDAD Y/O ABORTO','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (9,4,'LICENCIA DE PATERNIDAD','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (10,4,'LICENCIA DE MATERNIDAD O PATERNIDAD COMPARTIDA / FLEXIBLE','ACTIVO',USER,SYSDATE);
INSERT INTO  RHU.SBT_INCAPACIDAD VALUES (11,4,'LICENCIA DE MATERNIDAD POR EXTENSIÓN','ACTIVO',USER,SYSDATE);


COMMIT;

/